### ISSUE TITLE
Build issues in a clean environment

### ISSUE THREAD

**Issue by stuarteberg** [google/tensorstore#2] opened 2020-04-13 19:35 UTC
I tried to install `tensorstore` in a clean `CentOS` 8 container, but I run into a compilation error.  The container is using `gcc-c++-8.3.1` and `python36-3.6.8`.

<details>

<summary>Here's the error</summary>

```
    tensorstore/driver/neuroglancer_precomputed/driver.cc: In member function 'virtual tensorstore::Result<tensorstore::IndexTransform<> > tensorstore::internal_neuroglancer_precomputed::{anonymous}::DataCacheStateBase::GetExternalToInternalTransform(const void*, std::size_t)':
    tensorstore/driver/neuroglancer_precomputed/driver.cc:209:52: error: no matching function for call to 'tensorstore::IndexTransformBuilder<>::input_labels(<brace-enclosed initializer list>)'
         builder.input_labels({"x", "y", "z", "channel"});
                                                        ^
    In file included from tensorstore/driver/neuroglancer_precomputed/driver.cc:26:
    ./tensorstore/index_space/index_transform_builder.h:480:32: note: candidate: 'tensorstore::span<std::__cxx11::basic_string<char>, Count> tensorstore::IndexTransformBuilder<InputRank, OutputRank>::input_labels() [with long int InputRank = -1; long int OutputRank = -1]'
       span<std::string, InputRank> input_labels() {
                                    ^~~~~~~~~~~~
    ./tensorstore/index_space/index_transform_builder.h:480:32: note:   candidate expects 0 arguments, 1 provided
    ./tensorstore/index_space/index_transform_builder.h:496:3: note: candidate: 'template<class Labels> absl::enable_if_t<tensorstore::internal_index_space::IsStaticExtentCompatibleWithRange<InputRank, Indices>::value, tensorstore::IndexTransformBuilder<InputRank, OutputRank>&> tensorstore::IndexTransformBuilder<InputRank, OutputRank>::input_labels(const Labels&) [with Labels = Labels; long int InputRank = -1; long int OutputRank = -1]'
       input_labels(const Labels& labels) {
       ^~~~~~~~~~~~
    ./tensorstore/index_space/index_transform_builder.h:496:3: note:   template argument deduction/substitution failed:
    tensorstore/driver/neuroglancer_precomputed/driver.cc:209:52: note:   couldn't deduce template parameter 'Labels'
         builder.input_labels({"x", "y", "z", "channel"});
                                                        ^
    In file included from tensorstore/driver/neuroglancer_precomputed/driver.cc:26:
    ./tensorstore/index_space/index_transform_builder.h:507:26: note: candidate: 'template<long unsigned int N> tensorstore::IndexTransformBuilder<InputRank, OutputRank>& tensorstore::IndexTransformBuilder<InputRank, OutputRank>::input_labels(const string_view (&)[N]) [with long unsigned int N = N; long int InputRank = -1; long int OutputRank = -1]'
       IndexTransformBuilder& input_labels(const absl::string_view (&labels)[N]) {
                              ^~~~~~~~~~~~
    ./tensorstore/index_space/index_transform_builder.h:507:26: note:   template argument deduction/substitution failed:
    tensorstore/driver/neuroglancer_precomputed/driver.cc:209:52: note:   mismatched types 'std::basic_string_view<char>' and 'const char*'
         builder.input_labels({"x", "y", "z", "channel"});
                                                        ^
```

</details>

Here's my `Dockerfile`.

```dockerfile
FROM centos:8

RUN yum update -y \
 && yum install -y \
            python3 \
            platform-python-devel \
            gcc-c++ \
 && yum clean all

RUN python3 -m pip install tensorstore -vv

CMD [ "/bin/bash" ]
```

Any ideas?

**Comment by jbms** [comment] 2020-04-13 19:45
Per the installation instructions, you need GCC 9 or Clang 8.

On CentOS you can use the Redhat devtoolset-9 package:

```Dockerfile
RUN yum -y update && yum -y install \
    devtoolset-9-gcc-c++ \
    && yum clean all

ENV PATH="/opt/rh/devtoolset-9/root/usr/bin:$PATH"
```

I'm working on setting up some automation for building binary wheels using the manylinux2014 container as a base.  The following Dockerfile works for building wheels, though I haven't set up the automation yet:

```Dockerfile
ARG BASE=quay.io/pypa/manylinux2014_x86_64

FROM $BASE

LABEL description="A docker image for building portable Python linux binary wheels using modern GCC"
LABEL maintainer="jbms@google.com"

RUN yum -y update && yum -y install \
    devtoolset-9-gcc-c++ \
    && yum clean all

ENV PATH="/opt/rh/devtoolset-9/root/usr/bin:$PATH"
```

manylinux1 and manylinux2010 are more challenging since the pre-built Bazel binaries don't work (and also it is necessary to build a recent GCC from source, as the devtoolset-9 package isn't available).

Note: in the manylinux2014 container, the Python versions are in /opt/python/.

**Comment by stephenplaza** [comment] 2020-04-13 21:56
Hi Jeremy,

I tried both Stuart's CENTOS image and the one you specified above, and I cannot get tensorstore to install.   
 Maybe I am doing something slightly wrong.  Rather than debug what I am doing, I am happy to use whatever image works for you.  If you have a DockerFile that builds tensorstore, can you attach it?  Thanks!!

**Comment by stuarteberg** [comment] 2020-04-13 22:02
>Per the installation instructions, you need GCC 9 or Clang 8.

Ah, I missed that.  Thanks!

>I tried both Stuart's CENTOS image and the one you specified above, and I cannot get tensorstore to install.

The following Dockerfile works for me.  (Add `python3` and `python3-devel`)

```dockerfile
ARG BASE=quay.io/pypa/manylinux2014_x86_64

FROM $BASE

LABEL description="A docker image for building portable Python linux binary wheels using modern GCC"
LABEL maintainer="jbms@google.com"

RUN yum -y update && yum -y install \
    python3 \
    python3-devel \
    devtoolset-9-gcc-c++ \
    && yum clean all

ENV PATH="/opt/rh/devtoolset-9/root/usr/bin:$PATH"

RUN python3 -m pip install tensorstore -vv

CMD [ "/bin/bash" ]
```

**Comment by stephenplaza** [comment] 2020-04-15 16:51
When I build this container, I get a runtime error.  A symbol cannot be found.  Is there another path that should be set?

> import tensorstore as ts

  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/tensorstore/__init__.py", line 18, in <module>
    from ._tensorstore import *
ImportError: /usr/local/lib64/python3.6/site-packages/tensorstore/_tensorstore.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTINSt6thread6_StateE

**Comment by stuarteberg** [comment] 2020-04-15 18:36
The easiest thing to try is probably just to start with a base image for Ubuntu 19.10, which uses gcc-9 by default.

**Comment by jbms** [comment] 2020-04-15 18:39
I can reproduce this, and I'm looking into this.

Building a wheel inside the container then using it outside the container works on my system, but my system libstdc++.so.6 contains that symbol, while it is missing in /lib64/libstdc++.so.6 inside the container.

I think it might have something to do with the unusual way in which the devtoolset-9 package was created in order to provide a newer compiler on top of an older base system.

I think stuart's suggestion is a good one --- if you just want to use tensorstore inside a container, using a more recent base image which has a gcc-9 package available will almost certainly work.

Still, I'll try to get to the bottom of this since I do want tensorstore packages to be buildable for older systems.

**Comment by stuarteberg** [comment] 2020-04-15 19:07
In the meantime, this container builds successfully:

```dockerfile
FROM ubuntu:19.10

RUN apt-get update \
 && apt-get install -y python3-dev \
                       python3-pip \
                       build-essential

RUN python3 -m pip install tensorstore -vv

RUN python3 -c 'import tensorstore'

CMD [ "/bin/bash" ]
```

**Comment by jbms** [comment] 2020-04-15 19:54
This appears to be due to https://github.com/bazelbuild/bazel/issues/10327

While that bug is listed as closed, the issue has not actually been fixed in the most recent bazel release, 3.0.0.

In current bazel master (but unfortunately not yet in any released version), there is a flag `--incompatible_linkopts_to_linklibs` (https://github.com/bazelbuild/bazel/issues/10905) 

https://docs.bazel.build/versions/master/command-line-reference.html#flag--incompatible_linkopts_to_linklibs

Once that flag is available in a released version of bazel, I'll go ahead and enable it which should fix the problem.

In the meantime, the following workaround works:

```shell
BAZEL_LINKLIBS=-lstdc++ python3 -m pip install tensorstore -vv
```

I'll see about integrating this workaround into the build scripts so that it is not needed to be done by users.

**Comment by stephenplaza** [comment] 2020-04-19 22:12
As a follow-up to this, I tried using a special gcc9 container (the newest versions of ubuntu give me build problems for other things). The following fails (though it gets farther than my attempts before using gcc9) -- error message is quite cryptic and long.


FROM gcc:9.3
  
RUN apt-get update
RUN apt-get install -y python3-dev \
                       python3-pip \
                       build-essential

RUN python3 -m pip install numpy
RUN python3 -m pip install pillow
RUN python3 -m pip install gunicorn
RUN python3 -m pip install google-cloud-storage
RUN python3 -m pip install flask
RUN python3 -m pip install flask-cors
RUN python3 -m pip install scipy

RUN python3 -m pip install tensorstore -vv
CMD bash

**Comment by jbms** [comment] 2020-04-19 23:14
I can't reproduce the problem locally.  I copied that into a Dockerfile, ran docker build, which completed successfully, then ran the container and was able to import tensorstore.

**Comment by jbms** [comment] 2020-04-19 23:15
However, we hope to have binary package generation set up soon, which will simplify the installation.

**Comment by stephenplaza** [comment] 2020-04-20 01:08
That's really strange but I went to rebuild from scratch and it works now.  Sorry for that.  On the positive side, it is another docker container people can use if they couldn't use the latest red hat or ubuntu.

**Closed** 2020-04-29 02:32 UTC
