### ISSUE TITLE
possible memory leak

### ISSUE THREAD

**Issue by d-v-b** [google/tensorstore#14] opened 2020-09-03 15:40 UTC
This code generates a sharded image volume on the filesystem, then inserts data into the store in consecutive slabs. Memory usage goes up by ~10% every time that final saving loop completes. Is this a memory leak in the c++ code? The increasing memory consumption is a problem for a scaled-up version of this workflow.

```python
import numpy as np
import tensorstore as ts
import os
import psutil
from tqdm import tqdm
process = psutil.Process(os.getpid())
save_step = 64

kvstore_path = '/nrs/cosem/davis'
pth = 'memory_leak_test.precomputed'
chunk_size = (96,) * 3
shape = (2**12,2**11,2**11)  

# 16 GB of data
data = np.random.randint(0, 255, shape, dtype='uint8')
key = 's0'
resolution = np.array([1.0, 1.0, 1.0])

# sharding settings based on the google copy of hemibrain
sharding = {'@type': 'neuroglancer_uint64_sharded_v1',
           'preshift_bits': 9,
            'hash': 'identity',
            'minishard_index_encoding': 'gzip',
           'minishard_bits': 2,
           'shard_bits': 15}


spec = {'driver': 'neuroglancer_precomputed',
 'kvstore': {'driver': 'file', 'path': kvstore_path},
 'path': pth,
 'scale_metadata': {'size': data.shape,
  'resolution': resolution,
  'encoding': 'jpeg',
  'jpeg_quality': 100,
    'sharding': sharding,
  'chunk_size': chunk_size,
  'key': key,
  'voxel_offset': (0, 0, 0)},
 'multiscale_metadata': {'data_type': data.dtype.name,
  'num_channels': 1,
  'type': 'image'}}


arr = ts.open(spec=spec, create=True, delete_existing=True).result()
slices = [slice(idx * save_step, save_step * (idx + 1), None) for idx in range(data.shape[0]//save_step)]

print('start bytes: ', process.memory_info().rss)
for sl in tqdm(slices):
    arr[ts.d['channel'][0]][sl] = data[sl]
print('end bytes:   ', process.memory_info().rss)
```

**Comment by jbms** [comment] 2020-09-10 17:45
Thanks for sending this example --- I'll look into it and hopefully get to the bottom of it.

**Comment by jbms** [comment] 2020-09-12 02:55
Testing this myself, I'm not seeing significant growth when running this repeatedly, and using pprof also doesn't show any leaked memory.  (I ran pprof using a google-internal mechanism, I'm not sure how easily the open source pprof can be used with tensorstore.)

I might be missing something, though.  Can you share the outputs you are seeing from this?

I do see some amount of memory retained in the free page list by the memory allocator.  Additionally, because of how tensorstore uses threads, the arr[...] = data[s1] call may complete while a background thread still momentarily retains temporary buffers used for writing, such that it is possible the "end bytes" line is run before all memory is freed, but it should be freed immediately after.

Separately, maybe you are already aware of this and this is just an example for testing memory leaks, but the way you are writing the sharded precomputed format is very inefficient because the writes are not shard aligned.  When a write isn't shard aligned, tensorstore has to read each existing shard that is affected, modify it, and then rewrite it.  (Modifying in place is not possible.)  Therefore, there is a large write amplification factor here.

**Comment by d-v-b** [comment] 2020-09-15 22:57
This function logs memory use in bytes before and after the slab-wise saving of the array:

```python
def test_mem(nruns = 1):
    result = []
    for n in range(nruns):
        start_bytes = process.memory_info().rss
        for sl in tqdm(slices):
            arr[ts.d['channel'][0]][sl] = data[sl]
        stop_bytes = process.memory_info().rss
        result.append((start_bytes, stop_bytes))
    return result
```

Running this with `nruns=10` returned the following output (rows are runs, columns are pre- and post-saving memory use in bytes): 
```
[(17265467392, 21378891776),
 (21378891776, 22748270592),
 (22748270592, 22967046144),
 (22967046144, 23119863808),
 (23119863808, 23220432896),
 (23220436992, 23305125888),
 (23305129984, 23373012992),
 (23373012992, 23467606016),
 (23467606016, 24198459392),
 (24198459392, 24362373120)]
```
It looks like memory use is climbing each time the full array is saved; I'm running this again with 3x longer number of runs to see if I hit a plateau somewhere. 

And yes, I know this is a pathological way to write to the sharded format. I haven't gotten around to writing the logic for shard-aligned writes. (This would be a great feature for tensorstore :) )

**Comment by 2bndy5** [comment] 2022-05-03 05:40
Building from source displays a warning saying
>INFO: From Compiling tensorstore/kvstore/http/driver.cc:
path\to\tmp_dir\execroot\com_google_tensorstore\external\com_google_riegeli\riegeli\base\base.h(169) : warning C4722: 'riegeli::internal::UnreachableStream::~UnreachableStream': destructor never returns, potential memory leak

>INFO: From Compiling tensorstore/driver/stack/driver.cc:
path\to\tmp_dir\execroot\com_google_tensorstore\external\com_google_riegeli\riegeli\base\base.h(169) : warning C4722: 'riegeli::internal::UnreachableStream::~UnreachableStream': destructor never returns, potential memory leak

Not sure if that is related or a separate known issue.

**Comment by jbms** [comment] 2022-05-03 06:09
That is a spurious warning --- that type is only used in the false branch of an assertion when debugging is disabled:

https://github.com/google/riegeli/blob/5b42e9a8fc1a79d73836a471969b0d3c4d67d47c/riegeli/base/base.h#L258

**Comment by jbms** [comment] 2024-07-18 18:49
Closing for now since this is 4 years old and was unable to reproduce it.  Please reopen if it is still an issue.

**Closed by jbms** 2024-07-18 18:49 UTC
