### ISSUE TITLE
Including tensorstore into Qt cmake project

### ISSUE THREAD

**Issue by LarsKoeppel** [google/tensorstore#81] opened 2023-02-22 11:14 UTC
I want to include tensorstore in my Qt 6 cmake project. For this I have integrated the latest version with FetchContent: 
```
FetchContent_Declare(
  tensorstore
  URL "https://github.com/google/tensorstore/archive/refs/tags/v0.1.32.tar.gz"
)
FetchContent_MakeAvailable(tensorstore)
```

Environment: Windows 10 Pro 22H2
I installed NASM(2.16.01) and added it to the path variable.

When running cmake it crashes with the following output:
```
Running C:\Qt\Tools\CMake_64\bin\cmake.exe -S C:/Users/Lars/Documents/git/cuber -B C:/Users/Lars/Documents/git/build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug in C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug aus.
-- Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR) 
CMake Warning (dev) at C:/Qt/Tools/CMake_64/share/cmake-3.24/Modules/FetchContent.cmake:1267 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  CMakeLists.txt:56 (FetchContent_Declare)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Python3: C:/Users/Lars/AppData/Local/Programs/Python/Python310/python.exe (found version "3.10.7") found components: Interpreter 
-- Found Patch: C:/Program Files/Git/usr/bin/patch.exe  
-- [absl] Performing Test ABSL_INTERNAL_AT_LEAST_CXX17
-- [absl] Performing Test ABSL_INTERNAL_AT_LEAST_CXX17 - Success
-- [aom] Found Perl: C:/msys64/usr/bin/perl.exe (found version "5.36.0") 
Traceback (most recent call last):
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\evaluation.py", line 278, in get_optional_target_info
    rule_info.impl()
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\native_rules_cc.py", line 47, in <lambda>
    lambda: _cc_library_impl(context, target, **kwargs),
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\native_rules_cc.py", line 73, in _cc_library_impl
    common_options = handle_cc_common_options(
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\emit_cc.py", line 146, in handle_cc_common_options
    result[k] = _context.evaluate_configurable_list(cast(Any, value))
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\starlark\invocation_context.py", line 134, in evaluate_configurable_list
    evaluated: List[T] = self.evaluate_configurable(configurable)
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\starlark\invocation_context.py", line 119, in evaluate_configurable
    return cast(T, configurable.evaluate(self.evaluate_condition))
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\starlark\select.py", line 75, in evaluate
    raise ValueError("No matching condition")
ValueError: No matching condition

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\evaluation.py", line 278, in get_optional_target_info
    rule_info.impl()
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\native_rules_cc.py", line 47, in <lambda>
    lambda: _cc_library_impl(context, target, **kwargs),
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\native_rules_cc.py", line 73, in _cc_library_impl
    common_options = handle_cc_common_options(
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\emit_cc.py", line 117, in handle_cc_common_options
    cmake_deps = set(state.get_deps(resolved_deps))
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\evaluation.py", line 421, in get_deps
    deps.extend(self.get_dep(target))
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\evaluation.py", line 400, in get_dep
    info = self.get_optional_target_info(target_id)
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\evaluation.py", line 285, in get_optional_target_info
    raise ValueError(
ValueError: Error analyzing @org_videolan_dav1d//:headers  with RuleInfo(outs=[], impl=<function cc_library.<locals>.<lambda> at 0x000002B55E07D6C0>, kind='cc_library')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\evaluation.py", line 278, in get_optional_target_info
    rule_info.impl()
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\native_rules_cc.py", line 47, in <lambda>
    lambda: _cc_library_impl(context, target, **kwargs),
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\native_rules_cc.py", line 73, in _cc_library_impl
    common_options = handle_cc_common_options(
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\emit_cc.py", line 117, in handle_cc_common_options
    cmake_deps = set(state.get_deps(resolved_deps))
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\evaluation.py", line 421, in get_deps
    deps.extend(self.get_dep(target))
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\evaluation.py", line 400, in get_dep
    info = self.get_optional_target_info(target_id)
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\evaluation.py", line 285, in get_optional_target_info
    raise ValueError(
ValueError: Error analyzing @org_videolan_dav1d//:dav1d_core  with RuleInfo(outs=[], impl=<function cc_library.<locals>.<lambda> at 0x000002B55E07D5A0>, kind='cc_library')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake.py", line 41, in <module>
    sys.exit(bazel_to_cmake.main.main())
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\main.py", line 191, in main
    state.analyze(sorted(targets_to_analyze))
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\evaluation.py", line 181, in analyze
    self.get_target_info(target)
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\evaluation.py", line 291, in get_target_info
    info = self.get_optional_target_info(target_id)
  File "C:\Users\Lars\Documents\git\build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug\_deps\tensorstore-src\tools\cmake\bazel_to_cmake\evaluation.py", line 285, in get_optional_target_info
    raise ValueError(
ValueError: Error analyzing @org_videolan_dav1d//:dav1d  with RuleInfo(outs=[], impl=<function cc_library.<locals>.<lambda> at 0x000002B55E07D3F0>, kind='cc_library')
CMake Error at C:/Users/Lars/Documents/git/build-cuber-Desktop_Qt_6_4_0_MinGW_64_bit-Debug/_deps/dav1d-src/CMakeLists.txt:26 (execute_process):
  execute_process failed command indexes:

    1: "Child return code: 1"

-- Configuring incomplete, errors occurred!
```

Any ways to fix this?

**Comment by jbms** [comment] 2023-02-22 14:26
I believe the issue is caused by this set of conditions:

https://github.com/google/tensorstore/blob/a5833323833a268589d25e79571a479f4839f76c/third_party/org_videolan_dav1d/dav1d.BUILD.bazel#L180

Which compiler are you using?

**Comment by LarsKoeppel** [comment] 2023-02-22 16:58
I am using MinGW 11.2.0 64-bit. That is bundeld with Qt 6.4.2.

**Comment by jbms** [comment] 2023-02-22 18:09
Currently we only support MSVC on Windows --- we will have to add support for MinGW in order for it to work...

**Comment by LarsKoeppel** [comment] 2023-02-23 07:37
Ok. Then I will try to compile my project with MSVC...

How much effort would it be to support MinGW? And how long would it take?

**Comment by LarsKoeppel** [comment] 2023-03-07 13:50
I tried MSVC. But it didn't work the way I would like it to.

Are there any updates to the support of MinGW?

**Comment by jbms** [comment] 2023-03-07 13:53
Actually we have been working on it and it is close to working now.

**Comment by jbms** [comment] 2023-03-15 18:07
This is now fixed.  I recommend using lld rather than GNU ld, though, as GNU ld is very slow, especially in debug mode.

**Closed by jbms** 2023-03-15 18:07 UTC
