### ISSUE TITLE
Master does not compile on Linux

### ISSUE THREAD

**Issue by dzenanz** [google/tensorstore#112] opened 2023-09-06 18:16 UTC
c01efdcb2e685a70374b6434f00205ddb7ed3042 does not compile on my computer, nor the CI([PR 56](https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/pull/56), [build errors](https://open.cdash.org/viewBuildError.php?buildid=8969829)). Below is a relevant output from the local build. It compiles on Windows.

GCC 11.4.0 on Ubuntu 22.04. Python 3.10.12.

```log
$ ninja -k 99
[1/1433] Building CXX object _deps/upb-build/CMakeFiles/upb_upbc_protoc-gen-upb_stage0.dir/upbc/protoc-gen-upb.cc.o
FAILED: _deps/upb-build/CMakeFiles/upb_upbc_protoc-gen-upb_stage0.dir/upbc/protoc-gen-upb.cc.o 
/usr/bin/c++ -DCHROMIUM_ZLIB_NO_CHROMECONF -DUPB_BOOTSTRAP_STAGE0 -I/home/dzenan/zarr/ts-rel/_deps/absl-src -I/home/dzenan/zarr/ts-rel/_deps/upb-src -I/home/dzenan/zarr/ts-rel/_deps/upb-src/upb/reflection/stage0 -I/home/dzenan/zarr/ts-rel/_deps/utf8_range-src -I/home/dzenan/zarr/ts-rel/_deps/protobuf-src/src -I/home/dzenan/zarr/ts-rel/_deps/zlib-src -I/home/dzenan/zarr/ts-rel/_deps/zlib-src/contrib/optimizations -I/home/dzenan/zarr/ts-rel/_deps/upb-src/upbc/stage0 -O3 -DNDEBUG -fPIE -Wextra -Werror -Wno-unused-parameter -Wno-long-long -Wno-deprecated-declarations -Wno-sign-compare -Wno-unused-but-set-parameter -Wno-maybe-uninitialized -Wno-sequence-point -Wno-unknown-warning-option -fsized-deallocation -MD -MT _deps/upb-build/CMakeFiles/upb_upbc_protoc-gen-upb_stage0.dir/upbc/protoc-gen-upb.cc.o -MF _deps/upb-build/CMakeFiles/upb_upbc_protoc-gen-upb_stage0.dir/upbc/protoc-gen-upb.cc.o.d -o _deps/upb-build/CMakeFiles/upb_upbc_protoc-gen-upb_stage0.dir/upbc/protoc-gen-upb.cc.o -c /home/dzenan/zarr/ts-rel/_deps/upb-src/upbc/protoc-gen-upb.cc
In file included from /usr/include/string.h:535,
                 from /usr/include/c++/11/cstring:42,
                 from /home/dzenan/zarr/ts-rel/_deps/absl-src/absl/container/internal/container_memory.h:20,
                 from /home/dzenan/zarr/ts-rel/_deps/absl-src/absl/container/flat_hash_map.h:40,
                 from /home/dzenan/zarr/ts-rel/_deps/upb-src/upbc/protoc-gen-upb.cc:39:
In function ‘void* memcpy(void*, const void*, size_t)’,
    inlined from ‘void _upb_MiniTable_CopyFieldData(void*, const void*, const upb_MiniTableField*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/message/accessors_internal.h:113:13,
    inlined from ‘void _upb_Message_GetNonExtensionField(const upb_Message*, const upb_MiniTableField*, const void*, void*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/message/accessors_internal.h:213:31,
    inlined from ‘bool google_protobuf_MessageOptions_map_entry(const google_protobuf_MessageOptions*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/reflection/stage0/google/protobuf/descriptor.upb.h:3017:36:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:33: error: ‘void* __builtin___memcpy_chk(void*, const void*, long unsigned int, long unsigned int)’ writing 4 bytes into a region of size 1 overflows the destination [-Werror=stringop-overflow=]
   29 |   return __builtin___memcpy_chk (__dest, __src, __len,
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
   30 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘void* memcpy(void*, const void*, size_t)’,
    inlined from ‘void _upb_MiniTable_CopyFieldData(void*, const void*, const upb_MiniTableField*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/message/accessors_internal.h:116:13,
    inlined from ‘void _upb_Message_GetNonExtensionField(const upb_Message*, const upb_MiniTableField*, const void*, void*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/message/accessors_internal.h:213:31,
    inlined from ‘bool google_protobuf_MessageOptions_map_entry(const google_protobuf_MessageOptions*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/reflection/stage0/google/protobuf/descriptor.upb.h:3017:36:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:33: error: ‘void* __builtin___memcpy_chk(void*, const void*, long unsigned int, long unsigned int)’ writing 8 bytes into a region of size 1 overflows the destination [-Werror=stringop-overflow=]
   29 |   return __builtin___memcpy_chk (__dest, __src, __len,
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
   30 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘void* memcpy(void*, const void*, size_t)’,
    inlined from ‘void _upb_MiniTable_CopyFieldData(void*, const void*, const upb_MiniTableField*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/message/accessors_internal.h:119:13,
    inlined from ‘void _upb_Message_GetNonExtensionField(const upb_Message*, const upb_MiniTableField*, const void*, void*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/message/accessors_internal.h:213:31,
    inlined from ‘bool google_protobuf_MessageOptions_map_entry(const google_protobuf_MessageOptions*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/reflection/stage0/google/protobuf/descriptor.upb.h:3017:36:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:33: error: ‘void* __builtin___memcpy_chk(void*, const void*, long unsigned int, long unsigned int)’ writing 16 bytes into a region of size 1 overflows the destination [-Werror=stringop-overflow=]
   29 |   return __builtin___memcpy_chk (__dest, __src, __len,
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
   30 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘void* memcpy(void*, const void*, size_t)’,
    inlined from ‘void _upb_MiniTable_CopyFieldData(void*, const void*, const upb_MiniTableField*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/message/accessors_internal.h:113:13,
    inlined from ‘void _upb_Message_GetNonExtensionField(const upb_Message*, const upb_MiniTableField*, const void*, void*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/message/accessors_internal.h:213:31,
    inlined from ‘bool google_protobuf_MessageOptions_map_entry(const google_protobuf_MessageOptions*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/reflection/stage0/google/protobuf/descriptor.upb.h:3017:36,
    inlined from ‘void upbc::{anonymous}::GenerateGetters(upb::FieldDefPtr, const upbc::DefPoolPair&, absl::string_view, const NameToFieldDefMap&, const upbc::{anonymous}::Options&, upbc::Output&)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upbc/protoc-gen-upb.cc:605:48,
    inlined from ‘void upbc::{anonymous}::GenerateMessageInHeader(upb::MessageDefPtr, const upbc::DefPoolPair&, const upbc::{anonymous}::Options&, upbc::Output&)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upbc/protoc-gen-upb.cc:816:20:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:33: error: ‘void* __builtin___memcpy_chk(void*, const void*, long unsigned int, long unsigned int)’ writing 4 bytes into a region of size 1 overflows the destination [-Werror=stringop-overflow=]
   29 |   return __builtin___memcpy_chk (__dest, __src, __len,
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
   30 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘void* memcpy(void*, const void*, size_t)’,
    inlined from ‘void _upb_MiniTable_CopyFieldData(void*, const void*, const upb_MiniTableField*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/message/accessors_internal.h:116:13,
    inlined from ‘void _upb_Message_GetNonExtensionField(const upb_Message*, const upb_MiniTableField*, const void*, void*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/message/accessors_internal.h:213:31,
    inlined from ‘bool google_protobuf_MessageOptions_map_entry(const google_protobuf_MessageOptions*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/reflection/stage0/google/protobuf/descriptor.upb.h:3017:36,
    inlined from ‘void upbc::{anonymous}::GenerateGetters(upb::FieldDefPtr, const upbc::DefPoolPair&, absl::string_view, const NameToFieldDefMap&, const upbc::{anonymous}::Options&, upbc::Output&)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upbc/protoc-gen-upb.cc:605:48,
    inlined from ‘void upbc::{anonymous}::GenerateMessageInHeader(upb::MessageDefPtr, const upbc::DefPoolPair&, const upbc::{anonymous}::Options&, upbc::Output&)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upbc/protoc-gen-upb.cc:816:20:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:33: error: ‘void* __builtin___memcpy_chk(void*, const void*, long unsigned int, long unsigned int)’ writing 8 bytes into a region of size 1 overflows the destination [-Werror=stringop-overflow=]
   29 |   return __builtin___memcpy_chk (__dest, __src, __len,
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
   30 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘void* memcpy(void*, const void*, size_t)’,
    inlined from ‘void _upb_MiniTable_CopyFieldData(void*, const void*, const upb_MiniTableField*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/message/accessors_internal.h:119:13,
    inlined from ‘void _upb_Message_GetNonExtensionField(const upb_Message*, const upb_MiniTableField*, const void*, void*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/message/accessors_internal.h:213:31,
    inlined from ‘bool google_protobuf_MessageOptions_map_entry(const google_protobuf_MessageOptions*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/reflection/stage0/google/protobuf/descriptor.upb.h:3017:36,
    inlined from ‘void upbc::{anonymous}::GenerateGetters(upb::FieldDefPtr, const upbc::DefPoolPair&, absl::string_view, const NameToFieldDefMap&, const upbc::{anonymous}::Options&, upbc::Output&)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upbc/protoc-gen-upb.cc:605:48,
    inlined from ‘void upbc::{anonymous}::GenerateMessageInHeader(upb::MessageDefPtr, const upbc::DefPoolPair&, const upbc::{anonymous}::Options&, upbc::Output&)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upbc/protoc-gen-upb.cc:816:20:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:33: error: ‘void* __builtin___memcpy_chk(void*, const void*, long unsigned int, long unsigned int)’ writing 16 bytes into a region of size 1 overflows the destination [-Werror=stringop-overflow=]
   29 |   return __builtin___memcpy_chk (__dest, __src, __len,
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
   30 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘void* memcpy(void*, const void*, size_t)’,
    inlined from ‘void _upb_MiniTable_CopyFieldData(void*, const void*, const upb_MiniTableField*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/message/accessors_internal.h:119:13,
    inlined from ‘void _upb_Message_SetNonExtensionField(upb_Message*, const upb_MiniTableField*, const void*)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upb/message/accessors_internal.h:244:31,
    inlined from ‘void google_protobuf_compiler_CodeGeneratorResponse_set_supported_features(google_protobuf_compiler_CodeGeneratorResponse*, uint64_t)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upbc/stage0/google/protobuf/compiler/plugin.upb.h:427:36,
    inlined from ‘void upbc::Plugin::ReadRequest()’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upbc/plugin.h:185:5,
    inlined from ‘upbc::Plugin::Plugin()’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upbc/plugin.h:83:25,
    inlined from ‘int main(int, char**)’ at /home/dzenan/zarr/ts-rel/_deps/upb-src/upbc/protoc-gen-upb.cc:1710:16:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:33: error: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ reading 16 bytes from a region of size 8 [-Werror=stringop-overread]
   29 |   return __builtin___memcpy_chk (__dest, __src, __len,
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
   30 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dzenan/zarr/ts-rel/_deps/upb-src/upbc/protoc-gen-upb.cc: In function ‘int main(int, char**)’:
/home/dzenan/zarr/ts-rel/_deps/upb-src/upbc/protoc-gen-upb.cc:1708:5: note: source object ‘value’ of size 8
 1708 | int main(int argc, char** argv) {
      |     ^~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
cc1plus: all warnings being treated as errors
ninja: build stopped: cannot make progress due to previous errors.
```

**Comment by jbms** [comment] 2023-09-06 20:36
The issue here is that you are building with -Werror. Unfortunately we do not yet ensure that tensorstore builds without any warnings --- given that we support a number of different compilers and compiler versions and platforms and have a large number of dependencies it would be challenging to ensure all warnings are suppressed.

**Comment by laramiel** [comment] 2023-09-06 23:40
Additionally, upb has a few notes on this particular error.

https://github.com/protocolbuffers/upb/blob/41f83f7e042cd5810272cdd093f98fa3a4b55572/upb/message/internal/accessors.h#L43

They try and work around it by silencing the warning, but that doesn't work all the time.

**Comment by dzenanz** [comment] 2023-09-07 13:24
I am building with defaults, and not specifying `-Werror`, or any other non-default option. That comes either from tensorstore's or upb's build system.

**Comment by laramiel** [comment] 2023-09-07 22:09
And this is a pure tensorstore checkout? Or is this a CMake subproject?

If it's a subproject, the cmake variable will be inherited and you might need to specifically remove it, or just make sure it's not set.  You can see what happens py printing out the cmake variable.

I'm trying to reproduce this; the bazel build works with warnings

Create a VM running ubuntu-22.04-LTS. Something like:

```
PROJECT=myproject VMNAME=test \
gcloud compute instances create \
    $VMNAME \
    --project=$PROJECT \
    --zone=us-central1-a \
    --machine-type=e2-standard-4 \
    --network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default \
    --maintenance-policy=MIGRATE \
    --provisioning-model=STANDARD \
    --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append \
    --create-disk=auto-delete=yes,boot=yes,device-name=$VMNAME,image=projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20230829,mode=rw,size=250,type=projects/$PROJECT/zones/us-central1-a/diskTypes/pd-balanced \
    --no-shielded-secure-boot \
    --shielded-vtpm \
    --shielded-integrity-monitoring \
    --reservation-affinity=any
```

Install build prerequisites in the VM:

```
sudo apt-get update

sudo apt-get install -y --no-install-recommends \
      apt-transport-https \
      build-essential     \
      ca-certificates     \
      nasm                \
      ninja-build         \
      curl                \
      git                 \
      gnupg               \
      python3             \
      python3-dev         \
      python3-pip         \
      unzip               \
      wget

git clone https://github.com/google/tensorstore.git

```

Building with bazel, the warnings are printed but they do not stop the build.

```
cd tensorstore
./bazelisk.py build //tensorstore/...
```

**Comment by dzenanz** [comment] 2023-09-07 22:28
It happens both as pure tensor store and as subproject.

Written on cellphone, excuse my brevity.

**Comment by laramiel** [comment] 2023-09-07 22:33
As indicated in my prior comment, a clean checkout builds in both bazel and cmake, so it's something in your specific environment.  You should be able to copy my commands and validate for yourself.

**Comment by jbms** [comment] 2023-09-08 03:42
It does appear that upb sets `-Werror`:
https://github.com/protocolbuffers/upb/blob/e7430e66d6e51def2a88f0b66fdab62b0d9492c1/bazel/build_defs.bzl#L35

We can see in the command line printed that all of those flags are included in that order, which suggests that the `-Werror` is indeed coming from there.

That still leaves the question of exactly why it is failing for @dzenanz but not elsewhere, but we don't necessarily have to get to the bottom of that to fix it.

I'd say that we should:
1. Patch upb (ideally upstream) not to set `-Werror` when building it normally as a dependency; if desired, that should only be set for the project's own CI.
2. Ideally figure out how to properly suppress that warning, but given that we currently have many other warnings that is not necessarily a priority.

**Comment by laramiel** [comment] 2023-09-08 05:07
Hm, that is very curious. Looking at the generated `build.ninja` from the above repro, I see a very similar thing:

```
build _deps/upb-build/CMakeFiles/upb_upbc_protoc-gen-upb_stage0.dir/upbc/protoc-gen-upb.cc.o: CXX_COMPILER__upb_upbc_protoc-gen-upb_stage0_unscanned_ /home/lar/build/_deps/upb-src/upbc/protoc-gen-upb.cc || cmake_object_order_depends_target_upb_upbc_protoc-gen-upb_stage0
  DEFINES = -DCHROMIUM_ZLIB_NO_CHROMECONF -DUPB_BOOTSTRAP_STAGE0
  DEP_FILE = _deps/upb-build/CMakeFiles/upb_upbc_protoc-gen-upb_stage0.dir/upbc/protoc-gen-upb.cc.o.d
  FLAGS = -fPIE -Wextra -Werror -Wno-unused-parameter -Wno-long-long -Wno-deprecated-declarations -Wno-sign-compare -Wno-unused-but-set-parameter -Wno-maybe-uninitialized -Wno-sequence-point -Wno-unknown-warning-option -fsized-deallocation
  INCLUDES = -I/home/lar/build/_deps/absl-src -I/home/lar/build/_deps/upb-src -I/home/lar/build/_deps/upb-src/upb/reflection/stage0 -I/home/lar/build/_deps/utf8_range-src -I/home/lar/build/_deps/protobuf-src/src -I/home/lar/build/_deps/zlib-src -I/home/lar/build/_deps/zlib-src/contrib/optimizations -I/home/lar/build/_deps/upb-src/upbc/stage0
  OBJECT_DIR = _deps/upb-build/CMakeFiles/upb_upbc_protoc-gen-upb_stage0.dir
  OBJECT_FILE_DIR = _deps/upb-build/CMakeFiles/upb_upbc_protoc-gen-upb_stage0.dir/upbc
  TARGET_COMPILE_PDB = _deps/upb-build/CMakeFiles/upb_upbc_protoc-gen-upb_stage0.dir/
  TARGET_PDB = bin/upb_upbc_protoc-gen-upb_stage0.pdb
```

**Comment by laramiel** [comment] 2023-09-08 05:32
As for what to do, yes, patch upstream, but we'll want a local patch as well since upgrading protobuf/upb/grpc can be challenging due to the complex build processes.

**Comment by laramiel** [comment] 2023-09-08 05:36
Try applying the following patch and see if this solves your issue.

---

```
diff --git a/third_party/com_google_protobuf_upb/patches/werror.diff b/third_party/com_google_protobuf_upb/patches/werror.diff
new file mode 100644
index 0000000..3b829bc
--- /dev/null
+++ b/third_party/com_google_protobuf_upb/patches/werror.diff
@@ -0,0 +1,12 @@
+diff -u a/bazel/upb_proto_library.bzl b/bazel/upb_proto_library.bzl
+--- a/bazel/build_defs.bzl  2023-06-13 11:09:28
++++ b/bazel/build_defs.bzl  2023-09-07 22:14:58
+@@ -32,7 +32,7 @@
+ _DEFAULT_CPPOPTS.extend([
+     "-Wextra",
+     # "-Wshorten-64-to-32",  # not in GCC (and my Kokoro images doesn't have Clang)
+-    "-Werror",
++    # "-Werror",  # gcc https://github.com/google/tensorstore/issues/112
+     "-Wno-unused-parameter",
+     "-Wno-long-long",
+ ])
\ No newline at end of file
diff --git a/third_party/com_google_protobuf_upb/workspace.bzl b/third_party/com_google_protobuf_upb/workspace.bzl
index 997a49a..dd24a81 100644
--- a/third_party/com_google_protobuf_upb/workspace.bzl
+++ b/third_party/com_google_protobuf_upb/workspace.bzl
@@ -41,6 +41,9 @@
             # descriptor.proto, used for bootstrapping the cmake build, which also breaks
             # a big dependency on @com_google_protobuf.
             Label("//third_party:com_google_protobuf_upb/patches/bootstrap.diff"),
+
+            # Remove -Werror from upb; gcc fails with -Werror=stringop-overread
+            Label("//third_party:com_google_protobuf_upb/patches/werror.diff"),
         ],
         patch_args = ["-p1"],
         repo_mapping = {
```

**Comment by dzenanz** [comment] 2023-09-08 16:56
With this patch applied, the build with `ninja` succeeds.

**Closed** 2023-09-08 21:45 UTC
