### ISSUE TITLE
make fails when using c++ API 

### ISSUE THREAD

**Issue by asparsa** [google/tensorstore#163] opened 2024-06-06 21:21 UTC
I followed the Cmake integration document to run a simple tensorestore program in C++.
in spite of providing all of the build requirements, I encounter an error when trying to make my program.
 this is my CMake file :
```
 make_minimum_required(VERSION 3.27)
Project(test)
include(FetchContent)

FetchContent_Declare(
  tensorstore
  URL "https://github.com/google/tensorstore/archive/refs/tags/v0.1.59.tar.gz")

# Additional FetchContent_Declare calls as needed...

FetchContent_MakeAvailable(tensorstore)

# Define a target that depends on TensorStore...
add_executable(my_target src/main.cpp)
target_link_libraries(
  my_target
  PRIVATE
    tensorstore::tensorstore tensorstore::all_drivers
)
```

the errors it encounters are not being able to create a directory for example:

```
Built target Googleapis_google_api_expr_v1alpha1_syntax_proto__upbdefs_library
/u/asalimiparsa/test/build/_deps/envoy-build/c2959192/: No such file or directory
```
so I created that file manually and the same thing happened again and again!
Do you know what the problem is?

**Comment by asparsa** [comment] 2024-06-07 04:00
I saw the other issue with the same problem!
I checked and it works with ninja, but I wanted to see if it is only creating the directory issue. So I created the directory it was saying it's not there.  I created 38 paths in total and the make was complete!
I still wonder why ninja can create those paths and make won't!

**Comment by laramiel** [comment] 2024-06-07 15:43
What are the paths you had to create?  We could have bazel_to_cmake.py create those paths.
Look at https://github.com/google/tensorstore/tree/master/tools/cmake/bazel_to_cmake

Closing this as a duplicate of https://github.com/google/tensorstore/issues/151

**Closed by laramiel** 2024-06-07 15:43 UTC

**Comment by asparsa** [comment] 2024-06-07 16:07
I didn't save all of them but here are some example:
/u/asalimiparsa/test/build/_deps/udpa-build/10e5d71e/: No such file or directory
/u/asalimiparsa/test/build/_deps/envoy-build/d7d341d5/: No such file or directory
/u/asalimiparsa/test/build/_deps/envoy-build/12ec1b73/



/u/asalimiparsa/test/build/_deps/udpa-build/18a61f37/
/u/asalimiparsa/test/build/_deps/envoy-build/3ffcac10/
/u/asalimiparsa/test/build/_deps/envoy-build/b2a2733a/
/u/asalimiparsa/test/build/_deps/envoy-build/88915a3b/
/u/asalimiparsa/test/build/_deps/udpa-build/2fc9b2a5/

**Comment by laramiel** [comment] 2024-06-07 16:48
Ok, I suspect that I know what's going on here.  These are "hashed" output directories used in some protoc paths.

I think that when out_hash is set here: https://github.com/google/tensorstore/blob/2c1daeb010c0027f5769f75f4438c6c562ea303d/tools/cmake/bazel_to_cmake/native_aspect_proto.py#L130

Then we need to emit  `file(MAKE_DIRECTORY {output_dir})`

**Comment by asparsa** [comment] 2024-06-09 16:16
Yeah, you were right. I added `file(MAKE_DIRECTORY {output_dir})` to its return to make those directories.
I tested it with make and ninja, both work well. I can pull request for that.

**Comment by laramiel** [comment] 2024-06-10 15:43
I have already submitted a fix for this in https://github.com/google/tensorstore/commit/22a2396f6a97cf5a62b0197ccf8f61b689c8c0b5
